bot:
  name: "MyBot"

teamSpeak:
  host: "localhost"
  serverId: 1
  queryPort: 10011
  queryUsername: "serveradmin"
  queryPassword: "password"

database:
  host: "localhost"
  port: 3306
  databaseName: "teamspeakdata"
  user: "teamspeakdatauser"
  password: "password"